### ISSUE TITLE
Procédure de démarrage

### ISSUE THREAD

**Issue by kevinvennitti** [erasme/funkytown#1]
Comment lancer le dispositif ?
Comment faut-il configurer la machine ?

J'ai compilé FiducialDebug et l'ai lancé, et ensuite ?
De même, le Processing (lancé sur v3.0.0) me donne une erreur, est-ce à cause de l'absence de MIDI ?

**Comment by victorboquet** [comment]
Pour le démarrage, Martial aura plus de réponses que nous :) .
Avez-vous réussi a installer Ableton Live Lite pour faire marcher le MIDI ?
Essayez de vous authentifier avec l'email rmangenot@hotmail.fr et le mdp : rosalie.
Si il y a un problème avec la licence, je ferai un mail à Ableton pour pouvoir installer la license de Live sur d'autres machines.

**Comment by kevinvennitti** [comment]
@victorboquet La licence du compte _rmangenot@hotmail.fr_ fonctionne (sur mon ordi perso, il faudra tester sur la future machine du dispositif). Par contre @martial, j'ai toujours cette erreur sous Processing 3 :

![29-03-2016 10 52 02 - google chrome](https://cloud.githubusercontent.com/assets/9624530/14102693/69d45a0c-f59c-11e5-904f-d5cde94e657c.png)

**Comment by martial** [comment]
Bonjour, c'est pas évident à savoir – on dirait un problème lié à la librairie ou la version de Processing.
Es tu sur que toutes les librairies & versions sont à jour ?
